CREATE database 557Student;
USE 557Student;
CREATE table Personal_Info(Roll_Number int, Student_Name varchar(30),Address varchar(30),Date_of_birth date, Marks decimal(6,2));
desc Personal_Info;
DELETE FROM Personal_Info;
INSERT into Personal_Info values (557, 'Ram', 'vij','2001-05-26', 14.2);
INSERT into Personal_Info values (559, 'Sai','Gun','2002-01-27', 15);
INSERT into Personal_Info values (513, 'Gre', 'Gan', '2003-10-11',17);
INSERT into Personal_Info values (550, 'Sub', 'Vet','2004-11-11',18);
INSERT into Personal_Info values (123, 'Res', 'Hyd','2005-01-02',14);
SELECT * FROM Personal_Info;
ALTER TABLE Personal_Info add(Phone_Number bigint);
desc Personal_Info;
ALTER TABLE Personal_Info modify Phone_Number varchar(10);
desc Personal_Info;
ALTER TABLE Personal_Info drop Phone_Number;
desc Personal_Info;
ALTER TABLE Personal_Info add Phone_Number varchar(10);
desc Personal_Info;
UPDATE Personal_Info SET Phone_Number = 9876543210;
SELECT * FROM Personal_Info;
UPDATE Personal_Info SET Phone_Number = 9492904910 WHERE (Roll_Number = 559);
SELECT * FROM Personal_Info;
DELETE FROM Personal_Info WHERE Roll_Number = 550;
SELECT * FROM Personal_Info;
SELECT Roll_Number, Student_Name FROM Personal_Info;
SELECT * FROM Personal_Info WHERE Student_Name = 'Sai';
SELECT Roll_Number,Student_Name FROM Personal_Info WHERE Phone_Number = '9876543210';
CREATE TABLE Department(deptno int primary key, deptname varchar(20), Location varchar(50));
INSERT INTO Department values(101,'CSE','First Floor'),(102,'IT','Second Floor'),(103,'ECE','Third Floor');
SELECT * FROM Department;

ALTER TABLE Personal_Info ADD(Department_Num int references Department(deptno));
UPDATE Personal_Info SET Department_Num = 101;
UPDATE Personal_Info SET Department_Num = 103 WHERE Roll_Number = 513;
UPDATE Personal_Info SET Department_Num = 102 WHERE Roll_Number = 123;
SELECT * FROM Personal_Info;
